seed: 1337
deterministic: false
gpu: 3
name: null
debug: false
load_model: null
distillation: false
data:
  dataset_path: explainable_medical_coding/datasets/mimiciv_icd10.py
  target_columns:
  - diagnosis_codes
  - procedure_codes
  max_length: 6000
dataloader:
  max_batch_size: 2
  batch_size: 2
  num_workers: 0
  drop_last: false
  pin_memory: false
  batch_sampler:
    name: BySequenceLengthSampler
    configs:
      bucket_boundaries:
      - 400
      - 600
      - 800
      - 1000
      - 1200
      - 1400
      - 1600
      - 1800
      - 2000
      - 2200
      - 2600
      - 3000
      - 3400
      - 4000
      - 5000
model:
  name: PLMICD
  autoregressive: false
  configs:
    model_path: answerdotai/ModernBERT-base
    chunk_size: 128
    cross_attention: true
    loss: binary_cross_entropy
    lambda_1: 0.0
    scale: 1
    mask_input: false
trainer:
  name: Trainer
  epochs: 20
  validate_on_training_data: true
  print_metrics: false
  use_amp: true
  threshold_tuning: true
  clip_grad_norm: 1
  clip_value: 10
optimizer:
  name: AdamW
  configs:
    lr: 5.0e-05
    weight_decay: 0
lr_scheduler:
  name: linear
  configs:
    warmup: 0.1
metrics:
- name: F1Score
  configs:
    average: micro
- name: F1Score
  configs:
    average: macro
- name: Recall
  configs:
    average: micro
- name: Recall
  configs:
    average: macro
- name: Precision
  configs:
    average: micro
- name: Precision
  configs:
    average: macro
- name: FPR
  configs:
    average: micro
- name: FPR
  configs:
    average: macro
- name: ExactMatchRatio
  configs: {}
- name: Precision_K
  configs:
    k: 5
- name: Precision_K
  configs:
    k: 8
- name: Precision_K
  configs:
    k: 15
- name: Recall_K
  configs:
    k: 5
- name: Recall_K
  configs:
    k: 10
- name: Recall_K
  configs:
    k: 15
- name: MeanAveragePrecision
  configs: {}
- name: PrecisionAtRecall
  configs: {}
- name: AUC
  configs:
    average: micro
- name: AUC
  configs:
    average: macro
- name: LossMetric
  configs: {}
callbacks:
- name: WandbCallback
  configs:
    project: explainable-medical-coding
    entity: null
- name: SaveBestModelCallback
  configs:
    split: validation
    target: all
    metric: map
- name: EarlyStoppingCallback
  configs:
    split: validation
    target: all
    metric: map
    patience: 3
loss:
  name: binary_cross_entropy_loss
  configs: {}
